[dependencies]
runner = "../zig-out/bin/dependencies"
data = [
  "org.slf4j:slf4j-api:2.0.17",
  "com.hkupty.penna:penna-core:0.9.1"
]

[sources]
runner = "../zig-out/bin/sources"
data = [
  "./src/main/java/"
]

[compile]
runner = "../zig-out/bin/compile"
dependsOn = ["dependencies", "sources"]

[compile.data]
targetVersion = 21
sourceVersion = 21

# Virtual step, just triggers the execution of the previous steps
[build]
runner = "../zig-out/bin/javarun"
dependsOn = ["dependencies", "sources", "compile"]

[build.data]
mainClass = "stuff.Stuff"
