[dependencies]
runner = "../zig-out/bin/dependencies"
data = [
  "com.hkupty.penna:penna-core:0.9.1",
  "org.slf4j:slf4j-api:2.0.17"
]

[sources]
runner = "../zig-out/bin/sources"
data = [
  "./src/main/java/"
]

[compile]
runner = "../zig-out/bin/compile"
dependsOn = ["dependencies", "sources"]

[compile.data]
targetVersion = 24
sourceVersion = 24
args = [
  "--Werror"
]

# Virtual step, just triggers the execution of the previous steps
[build]
dependsOn = ["dependencies", "sources", "compile"]
